### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by varvarasd** [sunyang713/react-fadethrough#1]
Hi,

I'm getting this error:
`TypeError: Cannot read property 'string' of undefined`
My code below
```
<FadeThrough
                        width={'800px'}
                        height= {'600px'}
                        delay={ 5000 }
                        >
```

Error location:
`react-fadethrough/dist/FadeThroughContainer.js:86`
```
FadeThroughContainer.propTypes = {
> 86 |   width: _react2.default.PropTypes.string.isRequired,
  87 |   height: _react2.default.PropTypes.string.isRequired,
  88 |   delay: _react2.default.PropTypes.number.isRequired
  89 | };
```

Any ideas?

Many thanks

**Comment by sunyang713** [comment]
Hey, thanks for bringing this up. Sorry I got back to you so late. I'm looking into it now, I'll see what I can find.

**Comment by sbglasius** [comment]
Same issue for me. Did you find a fix for it?

**Comment by sunyang713** [comment]
ah, I know what it is. are you using React ^16? In React 16 they removed PropTypes. So Proptypes would be "undefined." I'm probably going to update this package to remove proptypes. I can still have checks on the props to make sure they're provided, but it will be even more light weight.

**Comment by sunyang713** [comment]
Okay, I just pushed and published a new version of the module that simplifies things and should fix this error. Since there are breaking changes, I've changed the version to 2.0.0 so you'll have to reinstall this package:

```
npm install --save react-fadethrough@latest
```

Here's the breaking change: https://github.com/sunyang713/react-fadethrough/releases/tag/v2.0.0
